# Generated by Django 2.1.7 on 2019-03-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='api接口名')),
                ('remark', models.CharField(blank=True, help_text='备注说明', max_length=255, null=True, verbose_name='备注说明')),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qps', models.IntegerField(verbose_name='qps值')),
                ('rt', models.IntegerField(verbose_name='rt值')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('api', models.ForeignKey(on_delete='所属接口', to='full_test.api')),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='应用名')),
                ('remark', models.CharField(blank=True, help_text='备注说明', max_length=255, null=True, verbose_name='备注说明')),
            ],
        ),
        migrations.AddField(
            model_name='api',
            name='service',
            field=models.ForeignKey(on_delete='所属应用', to='full_test.service'),
        ),
    ]
