# Generated by Django 2.1.7 on 2019-03-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('full_test', '0004_auto_20190312_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='all',
            field=models.IntegerField(default=1222, verbose_name='全站qps'),
        ),
    ]
